
birth_year = 1990
birth_month = 1
birth_day = 15
document_hash = "0x7ef9ddcac2711e1df3c9f27e766a5c7745138f2e280ef8545e453ed561a9b57f"
salt = "52539ef9da8f628c083f97b051c8359e507f7d935aa9f60c729eff2f06f37dec"
